name: example
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  chopper: 8.4.0
  collection: 1.19.1
  http: 1.5.0
  json_annotation: 4.9.0

dev_dependencies:
  swagger_dart_code_generator:
    path: ../
  chopper_generator: 8.4.0
  build_runner: 2.10.1
  json_serializable: 6.11.1
  lints: 6.0.0
