name: swagger_dart_code_generator

version: 4.1.0

homepage: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
repository: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
issue_tracker: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

description: Have you been turned into a problem with writing code for Http
  requests? This package can help. It has all of the Http and model codegen
  functionality you have been looking for.

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  build: ^2.5.4
  markdown: ^7.3.0
  recase: ^4.1.0
  json_annotation: ^4.9.0
  universal_io: ^2.2.2
  collection: ^1.19.1
  dart_style: ^2.3.2
  code_builder: ^4.11.0
  path: ^1.9.1
  http: ^1.6.0
  yaml: ^3.1.0

#  build: ^2.2.1
#    path: ^1.8.0
#    markdown: ">=5.0.0 <8.0.0"
#    recase: ^4.0.0
#    json_annotation: ^4.4.0
#    universal_io: ^2.0.4
#    collection: ^1.15.0
#    dart_style: ^2.2.1
#    code_builder: ^4.1.0
#    http: ^1.0.0
#    yaml: ^3.1.0

#new:
#  build: ^2.5.4
#  markdown: ^7.3.0
#  recase: ^4.1.0
#  json_annotation: ^4.9.0
#  universal_io: ^2.2.2
#  collection: ^1.19.1
#  dart_style: ^3.1.2
#  code_builder: ^4.11.0
#  path: ^1.9.1
#  http: ^1.3.0
#  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.8.0
  remove_from_coverage: ^2.0.0
  test: ^1.26.3
  lints: ^5.0.0
  chopper_generator: ^8.2.0
