name: swagger_dart_code_generator

version: 1.6.7

homepage: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
repository: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
issue_tracker: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues

description: Have you been turned into a problem with writing code for Http
  requests? This package can help. It has all of the Http and model codegen
  functionality you have been looking for.

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  build: ^1.6.3
  path: ^1.8.0
  markdown: ^4.0.0
  recase: ^4.0.0-nullsafety.0
  json_annotation: ^4.0.0
  build_runner: ^1.11.1
  meta: ^1.3.0
  build_config: ^0.4.5
  universal_io: ^2.0.0-nullsafety.2
  dart_style: ^1.3.13

dev_dependencies:
  json_serializable: ^4.0.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  test: any

dependency_overrides:
  analyzer: ^1.0.0
