name: swagger_dart_code_generator

version: 2.5.5

homepage: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
repository: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
issue_tracker: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues

description: Have you been turned into a problem with writing code for Http
  requests? This package can help. It has all of the Http and model codegen
  functionality you have been looking for.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.2.1
  path: ^1.8.0
  markdown: ^5.0.0
  recase: ^4.0.0
  json_annotation: ^4.4.0
  universal_io: ^2.0.4
  collection: ^1.15.0
  dart_style: ^2.2.1
  code_builder: ^4.1.0
  http: ^0.13.4
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  remove_from_coverage: ^2.0.0
  test: ^1.20.1
  lints: ^1.0.1
 
